# Generated by Django 4.2.7 on 2025-06-14 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_id', models.CharField(max_length=100, unique=True)),
                ('user_type', models.CharField(choices=[('patient', 'Patient'), ('staff', 'Hospital Staff'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('current_state', models.CharField(default='new', max_length=50)),
                ('session_data', models.JSONField(default=dict)),
                ('is_authenticated', models.BooleanField(default=False)),
                ('auth_token', models.TextField(blank=True, null=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_sessions',
            },
        ),
        migrations.CreateModel(
            name='BotMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing')], max_length=20)),
                ('message_content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usersession')),
            ],
            options={
                'db_table': 'bot_messages',
                'ordering': ['-timestamp'],
            },
        ),
    ]
